name: mobile_image_gallery_app
description: "mobile application for iamge gerllery app"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.11.0


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  #Design
  text_scroll: 0.2.0
  flutter_svg: 2.0.10+1
  vector_graphics: 1.1.11
  vector_graphics_compiler: 1.1.11

  #Responsive
  flutter_screenutil: 5.9.3
  auto_size_text: 3.0.0


  #Translation
  easy_localization: 3.0.8
  intl: 0.20.2

  #State Management
  equatable: 2.0.7
  reactive_forms: ^18.1.1
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0

  #Navigation
  go_router: ^14.6.2

  share_plus: ^10.1.2






  #network
  http: ^1.2.2
  dio: ^5.4.0
  pretty_dio_logger: ^1.4.0
  injectable: ^2.4.1
  dartz: ^0.10.1

  #Storage
  shared_preferences: ^2.3.3




  skeletonizer: ^2.1.0+1


  cached_network_image: ^3.4.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.7.0
  freezed: ^3.0.0
  json_serializable: ^6.8.0
  flutter_gen_runner: ^5.11.0
  flutter_lints: ^6.0.0
  injectable_generator: ^2.4.1

flutter:

  uses-material-design: true



  # Assets
  assets:
    - assets/images/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/ciro/Cairo-VariableFont_slnt,wght.ttf

flutter_gen:
  output: lib/gen/
  line_length: 120
  integrations:
    flutter_svg: true
  assets:
    outputs:
      class_name: Assets